/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import Entity.HoaDon;
import Entity.HoaDonChiTiet;
import dao.HoaDonCTDao;
import dao.HoaDonDao;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class BaoTri extends javax.swing.JInternalFrame {
    DefaultTableModel mol;
    HoaDonDao dao= new HoaDonDao();

    /**
     * Creates new form BaoTri
     */
    public BaoTri() {
        initComponents();
        init();
    }
    
    void init(){
        mol= (DefaultTableModel)tblDanhsach.getModel();
        mol.setRowCount(0);
        List<HoaDon> list= dao.selectByMaSan(QuanLySanBong.maSan);
        for (HoaDon hd : list) {
            mol.addRow(new Object[]{hd.getMaHD(),hd.getHoTenKH(),hd.getSoDienThoai(),hd.getEmail(),hd.getNgayThanhToan()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhsach = new javax.swing.JTable();

        setClosable(true);
        setTitle("DANH SÁCH LỊCH ĐẶT");

        tblDanhsach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Họ Tên Khách Hàng", "Số Điện Thoại", "Email", "Ngày Thanh Toán"
            }
        ));
        jScrollPane1.setViewportView(tblDanhsach);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDanhsach;
    // End of variables declaration//GEN-END:variables
}
