/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import Entity.KhachHang;
import Entity.NhanVien;
import dao.KhachHangDao;
import dao.NhanVienDao;
//import ui.QuenMatKhauJInternalFrame;
import utils.Auth;
import utils.MsgBox;

/**
 *
 * @author sonho
 */
public class DangNhap extends javax.swing.JDialog {
    int check = 1 ;
    /**
     * Creates new form DangNhap
     */
    public DangNhap(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTaikhoan = new javax.swing.JTextField();
        txtMatkhau = new javax.swing.JPasswordField();
        btnThoat = new javax.swing.JButton();
        btnDangNhap = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Đăng Nhập");

        jPanel1.setLayout(null);
        jPanel1.add(txtTaikhoan);
        txtTaikhoan.setBounds(30, 50, 260, 30);
        jPanel1.add(txtMatkhau);
        txtMatkhau.setBounds(30, 140, 260, 30);

        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jPanel1.add(btnThoat);
        btnThoat.setBounds(170, 200, 120, 40);

        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        jPanel1.add(btnDangNhap);
        btnDangNhap.setBounds(30, 200, 120, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Mật khẩu");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 100, 100, 25);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Tài khoản");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 10, 120, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/anhbong.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 454, 260);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        check();
        if (check==1) {
            DangNhap();
        }
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        Ketthuc();
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DangNhap dialog = new DangNhap(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtMatkhau;
    private javax.swing.JTextField txtTaikhoan;
    // End of variables declaration//GEN-END:variables
    void init(){
        setLocationRelativeTo(null);
    }
    void DangNhap(){
        String manv = txtTaikhoan.getText().trim();
        String makh = txtTaikhoan.getText().trim();
        String matkhaunv = new String(txtMatkhau.getPassword()).trim();
        String matkhaukh = new String(txtMatkhau.getPassword()).trim();
        NhanVienDao daonv = new NhanVienDao();
        KhachHangDao daokh = new KhachHangDao();
        NhanVien nv = daonv.selectById(manv);
        KhachHang kh = daokh.selectById(makh);
        if (nv==null && kh==null) {
        MsgBox.alert(this,"Sai tài khoản đăng nhập");
        }else if(nv !=null && !matkhaunv.equals(nv.getMatKhau())){
            MsgBox.alert(this, "Sai Mật Khẩu !");
        }else if(kh !=null && !matkhaukh.equals(kh.getMatKhau())){
            MsgBox.alert(this, "Sai Mật Khẩu !");
        }
        if(nv != null && nv.getTrangThai()==false) {
            MsgBox.alert(this,"Nhân viên đã nghỉ việc");
        }
        else{
                Auth.user1 = nv;
                Auth.user2 = kh;
                this.dispose();
                MsgBox.alert(this,"Đăng nhập thành công" );
        }
    }
    void Ketthuc(){
        if (MsgBox.confirm(this, "Bạn có muốn kết thúc ứng dụng ???")) {
            System.exit(0);
        }
    }
    void check (){
        String ID = txtTaikhoan.getText();
        String Pass = new String (txtMatkhau.getPassword());
        if (ID.length()==0) {
            MsgBox.alert(this, "Bạn chưa có tài khoản đăng nhập");
            check=0;
            return;
        }else if (Pass.length()==0) {
            MsgBox.alert(this, "Bạn chưa có mật khẩu");
            check=0;
            return;
        }else {
            check=1;
        }
    }
}
