/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ktpm;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.Timer;
import utils.Auth;
import utils.MsgBox;
import utils.XImage;

/**
 *
 * @author sonho
 */
public class FormChinh extends javax.swing.JFrame {

    /**
     * Creates new form FormChinh
     */
    public FormChinh() {
        initComponents();
        init();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ToolBar = new javax.swing.JToolBar();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnDangNhap3 = new javax.swing.JButton();
        Separator02 = new javax.swing.JToolBar.Separator();
        btnTrangChu = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnQLSan = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnQuanLyHoaDon = new javax.swing.JButton();
        Separator01 = new javax.swing.JToolBar.Separator();
        btnDangNhap2 = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        btnQLThongKe = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        btnDangNhap1 = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        btnDangNhap = new javax.swing.JButton();
        Separator3 = new javax.swing.JToolBar.Separator();
        DesktopPane = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblDongHo = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnithongTinCaNhan = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnidangNhap = new javax.swing.JMenuItem();
        mniDangKy = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mniDangXuat = new javax.swing.JMenuItem();
        mniketThuc = new javax.swing.JMenuItem();
        MenuQuanLy = new javax.swing.JMenu();
        mniNhanVien = new javax.swing.JMenuItem();
        mniKhachHang = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        mniQLsanBong = new javax.swing.JMenuItem();
        mniHoaDon = new javax.swing.JMenuItem();
        mniQLLichSuDat = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mniQLThongKe = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mniLienHe = new javax.swing.JMenuItem();
        mniGioiThieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trang Chủ");

        ToolBar.setRollover(true);
        ToolBar.add(jSeparator2);

        btnDangNhap3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-exit-48 (1).png"))); // NOI18N
        btnDangNhap3.setText("Đăng Xuất");
        btnDangNhap3.setFocusable(false);
        btnDangNhap3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangNhap3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangNhap3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhap3ActionPerformed(evt);
            }
        });
        ToolBar.add(btnDangNhap3);
        ToolBar.add(Separator02);

        btnTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-home-48.png"))); // NOI18N
        btnTrangChu.setText("Trang Chủ");
        btnTrangChu.setFocusable(false);
        btnTrangChu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTrangChu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ToolBar.add(btnTrangChu);
        ToolBar.add(jSeparator3);

        btnQLSan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-football-48.png"))); // NOI18N
        btnQLSan.setText("Quản Lý Sân ");
        btnQLSan.setFocusable(false);
        btnQLSan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLSan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ToolBar.add(btnQLSan);
        ToolBar.add(jSeparator4);

        btnQuanLyHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-task-list-48.png"))); // NOI18N
        btnQuanLyHoaDon.setText("Quản Lý Hóa Đơn");
        btnQuanLyHoaDon.setFocusable(false);
        btnQuanLyHoaDon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQuanLyHoaDon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ToolBar.add(btnQuanLyHoaDon);
        ToolBar.add(Separator01);

        btnDangNhap2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-order-history-48.png"))); // NOI18N
        btnDangNhap2.setText("Quản Lý Lịch Sử Đặt Sân");
        btnDangNhap2.setFocusable(false);
        btnDangNhap2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangNhap2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ToolBar.add(btnDangNhap2);
        ToolBar.add(jSeparator10);

        btnQLThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-statistics-48.png"))); // NOI18N
        btnQLThongKe.setText("Quản Lý Thống Kê");
        btnQLThongKe.setFocusable(false);
        btnQLThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLThongKe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ToolBar.add(btnQLThongKe);
        ToolBar.add(jSeparator9);

        btnDangNhap1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-sign-up-48.png"))); // NOI18N
        btnDangNhap1.setText("Đăng Ký");
        btnDangNhap1.setFocusable(false);
        btnDangNhap1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangNhap1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ToolBar.add(btnDangNhap1);
        ToolBar.add(jSeparator11);

        btnDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-login-48.png"))); // NOI18N
        btnDangNhap.setText("Đăng Nhập");
        btnDangNhap.setFocusable(false);
        btnDangNhap.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangNhap.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        ToolBar.add(btnDangNhap);
        ToolBar.add(Separator3);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/20e5364117fedfa086ef (1).jpg"))); // NOI18N

        DesktopPane.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/i.png"))); // NOI18N
        jLabel1.setText("Hệ Thống Quản Lý ");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        lblDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Clock.png"))); // NOI18N
        lblDongHo.setText("11:41:17 AM");
        jPanel1.add(lblDongHo, java.awt.BorderLayout.LINE_END);

        jMenu1.setText("Hệ Thống ");

        mnithongTinCaNhan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnithongTinCaNhan.setText("Thông Tin Cá Nhân");
        jMenu1.add(mnithongTinCaNhan);
        jMenu1.add(jSeparator1);

        mnidangNhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnidangNhap.setText("Đăng Nhập");
        mnidangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnidangNhapActionPerformed(evt);
            }
        });
        jMenu1.add(mnidangNhap);

        mniDangKy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDangKy.setText("Đăng Ký");
        jMenu1.add(mniDangKy);
        jMenu1.add(jSeparator7);

        mniDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDangXuat.setText("Đăng Xuất");
        jMenu1.add(mniDangXuat);

        mniketThuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniketThuc.setText("Kết Thúc");
        jMenu1.add(mniketThuc);

        MenuBar.add(jMenu1);

        MenuQuanLy.setText("Quản Lý ");

        mniNhanVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniNhanVien.setText("Quản Lý Nhân Viên");
        MenuQuanLy.add(mniNhanVien);

        mniKhachHang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniKhachHang.setText("Quản Lý Khách Hàng");
        mniKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKhachHangActionPerformed(evt);
            }
        });
        MenuQuanLy.add(mniKhachHang);
        MenuQuanLy.add(jSeparator8);

        mniQLsanBong.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_7, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniQLsanBong.setText("Quản Lý Sân Bóng");
        MenuQuanLy.add(mniQLsanBong);

        mniHoaDon.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniHoaDon.setText("Quản Lý Hóa Đơn");
        MenuQuanLy.add(mniHoaDon);

        mniQLLichSuDat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniQLLichSuDat.setText("Quản Lý Lịch Sử Đặt Sân");
        MenuQuanLy.add(mniQLLichSuDat);

        MenuBar.add(MenuQuanLy);

        jMenu4.setText("Thống Kê");

        mniQLThongKe.setText("Quản Lý Thống Kê");
        jMenu4.add(mniQLThongKe);

        MenuBar.add(jMenu4);

        jMenu3.setText("Trợ Giúp ");

        mniLienHe.setText("Liên Hệ ");
        jMenu3.add(mniLienHe);

        mniGioiThieu.setText("Giới Thiệu Sản Phẩm");
        jMenu3.add(mniGioiThieu);

        MenuBar.add(jMenu3);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1527, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKhachHangActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mniKhachHangActionPerformed

    private void mnidangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnidangNhapActionPerformed
        // TODO add your handling code here:
        new DangNhapNV(this, true).setVisible(true);
    }//GEN-LAST:event_mnidangNhapActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        new DangNhapNV(this, true).setVisible(true);
        if (Auth.user2 != null) {
            ToolBar.remove(btnQLThongKe);
            ToolBar.remove(btnQuanLyHoaDon);
            MenuBar.remove(2);
            MenuQuanLy.remove(mniKhachHang);
            MenuQuanLy.remove(mniNhanVien);
            MenuQuanLy.remove(mniHoaDon);
            ToolBar.remove(Separator01);
            ToolBar.remove(Separator02);
        }
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnDangNhap3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhap3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDangNhap3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu MenuQuanLy;
    private javax.swing.JToolBar.Separator Separator01;
    private javax.swing.JToolBar.Separator Separator02;
    private javax.swing.JToolBar.Separator Separator3;
    private javax.swing.JToolBar ToolBar;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnDangNhap1;
    private javax.swing.JButton btnDangNhap2;
    private javax.swing.JButton btnDangNhap3;
    private javax.swing.JButton btnQLSan;
    private javax.swing.JButton btnQLThongKe;
    private javax.swing.JButton btnQuanLyHoaDon;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JMenuItem mniDangKy;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniGioiThieu;
    private javax.swing.JMenuItem mniHoaDon;
    private javax.swing.JMenuItem mniKhachHang;
    private javax.swing.JMenuItem mniLienHe;
    private javax.swing.JMenuItem mniNhanVien;
    private javax.swing.JMenuItem mniQLLichSuDat;
    private javax.swing.JMenuItem mniQLThongKe;
    private javax.swing.JMenuItem mniQLsanBong;
    private javax.swing.JMenuItem mnidangNhap;
    private javax.swing.JMenuItem mniketThuc;
    private javax.swing.JMenuItem mnithongTinCaNhan;
    // End of variables declaration//GEN-END:variables
    void init (){
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setIconImage(XImage.getAppIcon());
        new Chao(this, true).setVisible(true);
        new Timer(1000,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date now = new Date();
                SimpleDateFormat date = new SimpleDateFormat("hh:mm:ss a");
                String text = date.format(now);
                lblDongHo.setText(text);
               }
        }).start();
    }
}
