/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import Entity.HoaDon;
import Entity.HoaDonChiTiet;
import dao.HoaDonCTDao;
import dao.HoaDonDao;
import java.net.Authenticator;
import java.util.List;
import java.util.Properties;
import java.util.Random;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.table.DefaultTableModel;
import utils.MsgBox;

/**
 *
 * @author admin
 */
public class LichSuDatSan extends javax.swing.JInternalFrame {
    HoaDonCTDao dao= new HoaDonCTDao();
    DefaultTableModel mol;
    int x;
    int index=-1;

    /**
     * Creates new form LichSuDatSan
     */
    public LichSuDatSan() {
        initComponents();
        mol= (DefaultTableModel)tblDanhsach.getModel();
        mol.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhsach = new javax.swing.JTable();
        btnHuysan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        txtMaXacNhan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("Lịch Sử Đặt Sân");

        tblDanhsach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Hóa Đơn CT", "Mã sân", "Số Điện Thoại", "Mã hóa đơn", "Mã khung giờ", "Ngày đặt", "Giá tiền", "Trạng thái"
            }
        ));
        jScrollPane1.setViewportView(tblDanhsach);

        btnHuysan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/stop_1.png"))); // NOI18N
        btnHuysan.setText("Hủy đặt sân");
        btnHuysan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuysanActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhập Email Để Xem Lịch Đặt"));

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-search-24_1.png"))); // NOI18N
        btnTimKiem.setText("Xem lịch đặt");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtMaXacNhan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Mã xác nhận:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)
                        .addComponent(txtMaXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHuysan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHuysan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String p_email = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        if (txtEmail.getText().equals("")) {
            MsgBox.alert(this, "Email trống");
            return;
        } else if (txtEmail.getText().matches(p_email) == false) {
            MsgBox.alert(this, "Email không đúng định dạng");
            return;
        } else {
        xem();
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnHuysanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuysanActionPerformed
        // TODO add your handling code here:
        huy();
    }//GEN-LAST:event_btnHuysanActionPerformed

    void huy(){
        this.index= tblDanhsach.getSelectedRow();
        if(index>=0){
        String trangthai= String.valueOf(tblDanhsach.getValueAt(this.index, 7));
        if(trangthai.equals("Đã xác nhận")||trangthai.equals("Đã hủy")){
            MsgBox.alert(this, "Không thể hủy đặt sân bóng này!");
            return;
        }else{
        if(txtMaXacNhan.getText().equals("")){
            Random rd = new Random();
            this.x = rd.nextInt(999999) + 100000;
            System.out.println(this.x);
            try {
                Properties p = new Properties();
                p.put("mail.smtp.auth", "true");
                p.put("mail.smtp.starttls.enable", "true");
                p.put("mail.smtp.host", "smtp.gmail.com");
                p.put("mail.smtp.port", "587");

                String accountName = "bangnvph17685@fpt.edu.vn";
                String accountPassword = "Vanbang2002";
                Session s;
                s = Session.getInstance(p, new javax.mail.Authenticator() {
                    @Override
                    protected javax.mail.PasswordAuthentication getPasswordAuthentication() {
                        return new javax.mail.PasswordAuthentication(accountName, accountPassword);
                    }

                });

                Message msg = new MimeMessage(s);
                msg.setFrom(new InternetAddress(accountName));
                msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(txtEmail.getText()));
                msg.setSubject("Xác nhận email");
                msg.setText("Mã xác nhận của bạn là: " + this.x + "\n Hãy bảo mật thông tin này !");

                Transport.send(msg);
                MsgBox.alert(this, "Mã xác nhận đã được gửi tới email: " + txtEmail.getText()+"\n Vui lòng nhập mã để hủy sân");
            } catch (MessagingException ex) {
                ex.printStackTrace();
                MsgBox.alert(this, "Gửi thất bại, bị gián đoạn");
            }
        }else{
            if(txtMaXacNhan.getText().equals(String.valueOf(this.x))){
                int mahdct= Integer.valueOf(tblDanhsach.getValueAt(this.index, 0)+"");
                HoaDonChiTiet hdct2= dao.selectById(mahdct);
                hdct2.setTrangThai(2);
                dao.update(hdct2);
                MsgBox.alert(this, "Hủy sân thành công");
                xem();
            }else{
                MsgBox.alert(this, "Mã xác nhận không chính xác.");
            }
        }
        }
        }
    }
    
    void xem(){
        mol.setRowCount(0);
        List<HoaDonChiTiet> list= dao.selectHoaDonChiTietByHoaDon(txtEmail.getText());
        String trangthai;
        for (HoaDonChiTiet hdct : list) {
            if(hdct.getTrangThai()==0){
                trangthai= "Chờ xác nhận";
            }else if(hdct.getTrangThai()==1){
                trangthai= "Đã xác nhận";
            }else{
                trangthai= "Đã hủy";
            }
            mol.addRow(new Object[]{hdct.getMaHDCT(),hdct.getMaSan(),txtEmail.getText(),hdct.getMaHD(),hdct.getMaKG(),hdct.getNgayDat(),hdct.getGiaTien(),trangthai});
        }
        if(tblDanhsach.getRowCount()==0){
            MsgBox.alert(this, "Vui lòng kiểm tra lại email!");
            mol.setRowCount(0);
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuysan;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDanhsach;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaXacNhan;
    // End of variables declaration//GEN-END:variables
}

